### ISSUE TITLE
I believe, since the sn is always 0 for one-way xcall messages, using this criterion for identifying duplicate messages is not feasible.

### ISSUE THREAD

**Issue by pragyanshrestha-ibriz** [icon-project/centralised-relay#51]
I believe, since the sn is always 0 for one-way xcall messages, using this criterion for identifying duplicate messages is not feasible.
@AntonAndell

_Originally posted by @redlarva in https://github.com/icon-project/xcall-multi/pull/196#discussion_r1421956230_

**Comment by debendraoli** [comment]
We handled from centralized connection contract.
